Input
pariyar07/Waldo pull request #11
Opened 2022-02-06 18:59 UTC by pariyar07

2022-02-07 15:07 UTC, yogesh- approved these changes
Looks good to merge

2022-02-07 16:15 UTC, syed-shaida-hussain requested changes
Try using variables for colors and use relative units.

2022-02-07 16:15 UTC, syed-shaida-hussain commented on pages/input/input.css
> +    color: rgb(255, 255, 255);
try to use variable for color here as well

2022-02-07 16:15 UTC, syed-shaida-hussain commented on pages/input/input.css
> +
Don't repeat yourself . Make flex utility class and then use it everywhere.

2022-02-07 16:15 UTC, syed-shaida-hussain commented on pages/input/input.css
> +    background-color: rgb(225, 225, 225);
use variable for colors

2022-02-07 16:15 UTC, syed-shaida-hussain commented on pages/input/input.css
> +
try to use relative units instead of pixels.

2022-02-07 16:15 UTC, syed-shaida-hussain commented on pages/input/input.js
> +const container = document.querySelector('.container');
i think component library was to be made using HTML and CSS only.

2022-02-07 17:43 UTC, merged

2022-02-08 10:09 UTC, vaibhav18matere commented on pages/input/input.css
> +    justify-content: center;
can make separate class for it ex. `d-center`

2022-02-08 10:09 UTC, vaibhav18matere commented on pages/input/input.html
> +                <i id="err" class="fas fa-exclamation-circle"></i>
give proper ID names ex.` success` `error` to make it more clear