rating component added
pariyar07/Waldo pull request #13
Opened 2022-02-11 15:28 UTC by pariyar07

Added 4 types of ratings

2022-02-11 16:17 UTC, Tanay-J requested changes

2022-02-11 16:17 UTC, Tanay-J commented on styles/rating.css
> +}
Please use single class for set of properties which are being used multiple times, so as to avoid code repetition.

2022-02-12 12:17 UTC, yogesh- approved these changes
Looks good, few minor changes suggested

2022-02-12 12:17 UTC, yogesh- commented on styles/rating.css
> +}
use color variables

2022-02-12 12:17 UTC, yogesh- commented on styles/rating.css
> +.empty-rating, .filled-rating, .custom-rating, .emoji-rating{
make a class of flex and use that in all the divs where it is required, much faster than this.

2022-02-12 14:43 UTC, merged